CREATE DATABASE COMPANY
Use COMPANY

CREATE table CUSTOMERS(
    ID int,
    Name NVARCHAR(50) NOT NULL,
    Age SMALLINT,
    Address NVARCHAR(MAX),
    Salary DECIMAL(18,0)
    Constraint pk_ID PRIMARY KEY(ID)
)
